---
title: "Queensland Gaming Data Exploration"
author: "Ashley Betts"
date: "11/08/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

There is missing expenditure for November of 2013.

## R Markdown
```{r}
library(tidyr)
all_gamb_sum <- all_gambling_df %>%
  dplyr::select(-game_stream) %>% 
  group_by(x_month_year) %>%
  dplyr::summarise(total_expenditure=sum(player_expenditure))
total_egm_sum <- total_egm_df %>%
  dplyr::select(x_month_year,metered_win) %>%
  group_by(x_month_year) %>%
  dplyr::summarise(total_wins=sum(metered_win))
egm_flow <- join(all_gamb_sum,total_egm_sum)
egm_flow <- separate(egm_flow, x_month_year, c("Month", "Year"))
egm_flow_pct <- egm_flow %>% mutate(pay_pct = total_wins / total_expenditure)
egm_flow_sum <- egm_flow %>% group_by(Year) %>% dplyr::summarise(expend=sum(total_expenditure, na.rm = T),pay=sum(total_wins, na.rm=T),paypct=pay/expend)

# Check if there is any significant variance from the mean.
t.test(mean(egm_flow_sum$paypct)-egm_flow_sum$paypct)
# With p-value of 1 and 0 in the confidence interval we accept the null hypothesis (nothing is moving far from the mean)

ggplot(egm_flow_sum, aes(Year, expend, group=1)) + geom_line() + geom_line(aes(y=pay))

```

